# Change these first
owner: chunter99 # Your GitHub organization or username, where this repository lives
repo: was_checking_byupptime # The name of this repository

sites:
  - name: Alzam
    url: https://alzam.babysleep.co.kr
  - name: Babysleep
    url: https://www.babysleep.co.kr
  - name: Goodnightbaby
    url: https://www.goodnightbaby.org
  - name: goose-auth-api
    url: https://goose-auth-api.mooo.com/swagger-ui/index.html
assignees: # Users to assign downtime issues (optional)
  - chunter99  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /was_checking_byupptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Server-Status
  introTitle: "Web-Server Status"
  introMessage: 서버 상태 확인
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
